// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type MutationOptions, queryOptions } from "@tanstack/svelte-query"

import { client } from "../client.gen"
import {
	actOnMprisPlayer,
	controlBento,
	dismissNotification,
	focusNiriWorkspace,
	getApiMediaById,
	getConfiguredTimezone,
	getSystemStatus,
	invokeNotificationAction,
	listMprisPlayers,
	listNiriWorkspaces,
	listNotifications,
	lockSystem,
	logoutSystem,
	type Options,
	rebootSystem,
	resizeNotifications,
	setNotificationPaused,
	shutdownSystem,
	suspendSystem,
} from "../sdk.gen"
import type {
	ActOnMprisPlayerData,
	ActOnMprisPlayerError,
	ActOnMprisPlayerResponse,
	ControlBentoData,
	ControlBentoError,
	ControlBentoResponse,
	DismissNotificationData,
	DismissNotificationError,
	DismissNotificationResponse,
	FocusNiriWorkspaceData,
	FocusNiriWorkspaceError,
	FocusNiriWorkspaceResponse,
	GetApiMediaByIdData,
	GetConfiguredTimezoneData,
	GetConfiguredTimezoneResponse,
	GetSystemStatusData,
	GetSystemStatusResponse,
	InvokeNotificationActionData,
	InvokeNotificationActionError,
	InvokeNotificationActionResponse,
	ListMprisPlayersData,
	ListMprisPlayersResponse,
	ListNiriWorkspacesData,
	ListNiriWorkspacesResponse,
	ListNotificationsData,
	ListNotificationsError,
	ListNotificationsResponse,
	LockSystemData,
	LockSystemResponse,
	LogoutSystemData,
	LogoutSystemResponse,
	RebootSystemData,
	RebootSystemResponse,
	ResizeNotificationsData,
	ResizeNotificationsError,
	ResizeNotificationsResponse,
	SetNotificationPausedData,
	SetNotificationPausedError,
	SetNotificationPausedResponse,
	ShutdownSystemData,
	ShutdownSystemResponse,
	SuspendSystemData,
	SuspendSystemResponse,
} from "../types.gen"

export type QueryKey<TOptions extends Options> = [
	Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
		_id: string
		_infinite?: boolean
		tags?: ReadonlyArray<string>
	},
]

const createQueryKey = <TOptions extends Options>(
	id: string,
	options?: TOptions,
	infinite?: boolean,
	tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
	const params: QueryKey<TOptions>[0] = {
		_id: id,
		baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
	} as QueryKey<TOptions>[0]
	if (infinite) {
		params._infinite = infinite
	}
	if (tags) {
		params.tags = tags
	}
	if (options?.body) {
		params.body = options.body
	}
	if (options?.headers) {
		params.headers = options.headers
	}
	if (options?.path) {
		params.path = options.path
	}
	if (options?.query) {
		params.query = options.query
	}
	return [params]
}

export const getApiMediaByIdQueryKey = (options: Options<GetApiMediaByIdData>) =>
	createQueryKey("getApiMediaById", options)

export const getApiMediaByIdOptions = (options: Options<GetApiMediaByIdData>) =>
	queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiMediaByIdQueryKey>>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getApiMediaById({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: getApiMediaByIdQueryKey(options),
	})

export const listMprisPlayersQueryKey = (options?: Options<ListMprisPlayersData>) =>
	createQueryKey("listMprisPlayers", options)

export const listMprisPlayersOptions = (options?: Options<ListMprisPlayersData>) =>
	queryOptions<
		ListMprisPlayersResponse,
		DefaultError,
		ListMprisPlayersResponse,
		ReturnType<typeof listMprisPlayersQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await listMprisPlayers({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: listMprisPlayersQueryKey(options),
	})

export const actOnMprisPlayerMutation = (
	options?: Partial<Options<ActOnMprisPlayerData>>,
): MutationOptions<
	ActOnMprisPlayerResponse,
	ActOnMprisPlayerError,
	Options<ActOnMprisPlayerData>
> => {
	const mutationOptions: MutationOptions<
		ActOnMprisPlayerResponse,
		ActOnMprisPlayerError,
		Options<ActOnMprisPlayerData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await actOnMprisPlayer({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const listNotificationsQueryKey = (options?: Options<ListNotificationsData>) =>
	createQueryKey("listNotifications", options)

export const listNotificationsOptions = (options?: Options<ListNotificationsData>) =>
	queryOptions<
		ListNotificationsResponse,
		ListNotificationsError,
		ListNotificationsResponse,
		ReturnType<typeof listNotificationsQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await listNotifications({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: listNotificationsQueryKey(options),
	})

export const resizeNotificationsMutation = (
	options?: Partial<Options<ResizeNotificationsData>>,
): MutationOptions<
	ResizeNotificationsResponse,
	ResizeNotificationsError,
	Options<ResizeNotificationsData>
> => {
	const mutationOptions: MutationOptions<
		ResizeNotificationsResponse,
		ResizeNotificationsError,
		Options<ResizeNotificationsData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await resizeNotifications({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const dismissNotificationMutation = (
	options?: Partial<Options<DismissNotificationData>>,
): MutationOptions<
	DismissNotificationResponse,
	DismissNotificationError,
	Options<DismissNotificationData>
> => {
	const mutationOptions: MutationOptions<
		DismissNotificationResponse,
		DismissNotificationError,
		Options<DismissNotificationData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await dismissNotification({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const setNotificationPausedMutation = (
	options?: Partial<Options<SetNotificationPausedData>>,
): MutationOptions<
	SetNotificationPausedResponse,
	SetNotificationPausedError,
	Options<SetNotificationPausedData>
> => {
	const mutationOptions: MutationOptions<
		SetNotificationPausedResponse,
		SetNotificationPausedError,
		Options<SetNotificationPausedData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await setNotificationPaused({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const invokeNotificationActionMutation = (
	options?: Partial<Options<InvokeNotificationActionData>>,
): MutationOptions<
	InvokeNotificationActionResponse,
	InvokeNotificationActionError,
	Options<InvokeNotificationActionData>
> => {
	const mutationOptions: MutationOptions<
		InvokeNotificationActionResponse,
		InvokeNotificationActionError,
		Options<InvokeNotificationActionData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await invokeNotificationAction({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const controlBentoMutation = (
	options?: Partial<Options<ControlBentoData>>,
): MutationOptions<ControlBentoResponse, ControlBentoError, Options<ControlBentoData>> => {
	const mutationOptions: MutationOptions<
		ControlBentoResponse,
		ControlBentoError,
		Options<ControlBentoData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await controlBento({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const listNiriWorkspacesQueryKey = (options?: Options<ListNiriWorkspacesData>) =>
	createQueryKey("listNiriWorkspaces", options)

export const listNiriWorkspacesOptions = (options?: Options<ListNiriWorkspacesData>) =>
	queryOptions<
		ListNiriWorkspacesResponse,
		DefaultError,
		ListNiriWorkspacesResponse,
		ReturnType<typeof listNiriWorkspacesQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await listNiriWorkspaces({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: listNiriWorkspacesQueryKey(options),
	})

export const focusNiriWorkspaceMutation = (
	options?: Partial<Options<FocusNiriWorkspaceData>>,
): MutationOptions<
	FocusNiriWorkspaceResponse,
	FocusNiriWorkspaceError,
	Options<FocusNiriWorkspaceData>
> => {
	const mutationOptions: MutationOptions<
		FocusNiriWorkspaceResponse,
		FocusNiriWorkspaceError,
		Options<FocusNiriWorkspaceData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await focusNiriWorkspace({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const lockSystemMutation = (
	options?: Partial<Options<LockSystemData>>,
): MutationOptions<LockSystemResponse, DefaultError, Options<LockSystemData>> => {
	const mutationOptions: MutationOptions<
		LockSystemResponse,
		DefaultError,
		Options<LockSystemData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await lockSystem({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const suspendSystemMutation = (
	options?: Partial<Options<SuspendSystemData>>,
): MutationOptions<SuspendSystemResponse, DefaultError, Options<SuspendSystemData>> => {
	const mutationOptions: MutationOptions<
		SuspendSystemResponse,
		DefaultError,
		Options<SuspendSystemData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await suspendSystem({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const rebootSystemMutation = (
	options?: Partial<Options<RebootSystemData>>,
): MutationOptions<RebootSystemResponse, DefaultError, Options<RebootSystemData>> => {
	const mutationOptions: MutationOptions<
		RebootSystemResponse,
		DefaultError,
		Options<RebootSystemData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await rebootSystem({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const shutdownSystemMutation = (
	options?: Partial<Options<ShutdownSystemData>>,
): MutationOptions<ShutdownSystemResponse, DefaultError, Options<ShutdownSystemData>> => {
	const mutationOptions: MutationOptions<
		ShutdownSystemResponse,
		DefaultError,
		Options<ShutdownSystemData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await shutdownSystem({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const logoutSystemMutation = (
	options?: Partial<Options<LogoutSystemData>>,
): MutationOptions<LogoutSystemResponse, DefaultError, Options<LogoutSystemData>> => {
	const mutationOptions: MutationOptions<
		LogoutSystemResponse,
		DefaultError,
		Options<LogoutSystemData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await logoutSystem({
				...options,
				...fnOptions,
				throwOnError: true,
			})
			return data
		},
	}
	return mutationOptions
}

export const getSystemStatusQueryKey = (options?: Options<GetSystemStatusData>) =>
	createQueryKey("getSystemStatus", options)

export const getSystemStatusOptions = (options?: Options<GetSystemStatusData>) =>
	queryOptions<
		GetSystemStatusResponse,
		DefaultError,
		GetSystemStatusResponse,
		ReturnType<typeof getSystemStatusQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getSystemStatus({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: getSystemStatusQueryKey(options),
	})

export const getConfiguredTimezoneQueryKey = (options?: Options<GetConfiguredTimezoneData>) =>
	createQueryKey("getConfiguredTimezone", options)

export const getConfiguredTimezoneOptions = (options?: Options<GetConfiguredTimezoneData>) =>
	queryOptions<
		GetConfiguredTimezoneResponse,
		DefaultError,
		GetConfiguredTimezoneResponse,
		ReturnType<typeof getConfiguredTimezoneQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getConfiguredTimezone({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			})
			return data
		},
		queryKey: getConfiguredTimezoneQueryKey(options),
	})
