keys:
    - &extreme-creeper-jonagam ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFKcRyyxNuDUOd9RtuzYevGWKf0iMN0lGSmjc3Wdv3n/
    - &nixos-bill ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP9+Xfs7hetjrxuMkRJVGNNYFIGDjm8IPw7loqL+oiVu
creation_rules:
    - path_regex: hosts/extreme-creeper/secrets/jonahgam\.yaml
      key_groups:
          - age:
                - *extreme-creeper-jonagam
    - path_regex: hosts/nixos-bill/secrets/machine\.yaml
      key_groups:
          - age:
                - *nixos-bill
