formatter = "nixfmt"
top-level-blank-lines = 1

[args]
first = ["lib", "config", "pkgs", "inputs", "inputs'", "self", "self'"]
last = ["<defaulted>", "..."]

[lets]
sort = true

[attrs]
first = ["flake-file", "imports", "perSystem", "flake.grove"]
flatten = true
merge = true

[[overrides]]
path = "**.flake-file.inputs.*"
attrs.first = ["url", "inputs", "flake"]

[[overrides]]
path = "flake.grove"
attrs.first = ["types", "projectors", "overrides", "finalized"]

[[overrides]]
path = "flake.grove.projectors.**"
attrs.first = ["imports", "enable", "package", "settings"]

[[overrides]]
path = "flake.grove.projectors.**.homeManager"
attrs.last = ["home.persistence"]
