// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod"

import type {
	Client,
	ClientMeta,
	Options as Options2,
	RequestResult,
	ServerSentEventsResult,
	TDataShape,
} from "./client"
import { client } from "./client.gen"
import type {
	ActOnMprisPlayerData,
	ActOnMprisPlayerErrors,
	ActOnMprisPlayerResponses,
	ControlBentoData,
	ControlBentoErrors,
	ControlBentoResponses,
	DismissNotificationData,
	DismissNotificationErrors,
	DismissNotificationResponses,
	FocusNiriWorkspaceData,
	FocusNiriWorkspaceErrors,
	FocusNiriWorkspaceResponses,
	GetApiMediaByIdData,
	GetConfiguredTimezoneData,
	GetConfiguredTimezoneResponses,
	GetSystemStatusData,
	GetSystemStatusResponses,
	InvokeNotificationActionData,
	InvokeNotificationActionErrors,
	InvokeNotificationActionResponses,
	ListMprisPlayersData,
	ListMprisPlayersResponses,
	ListNiriWorkspacesData,
	ListNiriWorkspacesResponses,
	ListNotificationsData,
	ListNotificationsErrors,
	ListNotificationsResponses,
	LockSystemData,
	LockSystemResponses,
	LogoutSystemData,
	LogoutSystemResponses,
	RebootSystemData,
	RebootSystemResponses,
	ResizeNotificationsData,
	ResizeNotificationsErrors,
	ResizeNotificationsResponses,
	SetNotificationPausedData,
	SetNotificationPausedErrors,
	SetNotificationPausedResponses,
	ShutdownSystemData,
	ShutdownSystemResponses,
	StreamCavaData,
	StreamCavaErrors,
	StreamCavaResponse,
	StreamCavaResponses,
	StreamMprisPlayersData,
	StreamMprisPlayersErrors,
	StreamMprisPlayersResponse,
	StreamMprisPlayersResponses,
	StreamNiriEventsData,
	StreamNiriEventsErrors,
	StreamNiriEventsResponse,
	StreamNiriEventsResponses,
	StreamNotificationsData,
	StreamNotificationsErrors,
	StreamNotificationsResponse,
	StreamNotificationsResponses,
	SuspendSystemData,
	SuspendSystemResponses,
} from "./types.gen"
import {
	zActOnMprisPlayerBody,
	zActOnMprisPlayerPath,
	zActOnMprisPlayerResponse,
	zControlBentoBody,
	zControlBentoResponse,
	zDismissNotificationPath,
	zDismissNotificationResponse,
	zFocusNiriWorkspaceBody,
	zFocusNiriWorkspaceResponse,
	zGetApiMediaByIdPath,
	zGetConfiguredTimezoneResponse,
	zGetSystemStatusResponse,
	zInvokeNotificationActionPath,
	zInvokeNotificationActionResponse,
	zListMprisPlayersResponse,
	zListNiriWorkspacesResponse,
	zListNotificationsResponse,
	zLockSystemResponse,
	zLogoutSystemResponse,
	zRebootSystemResponse,
	zResizeNotificationsBody,
	zResizeNotificationsResponse,
	zSetNotificationPausedBody,
	zSetNotificationPausedPath,
	zSetNotificationPausedResponse,
	zShutdownSystemResponse,
	zStreamCavaResponse,
	zStreamMprisPlayersResponse,
	zStreamNiriEventsResponse,
	zStreamNotificationsResponse,
	zSuspendSystemResponse,
} from "./zod.gen"

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
	TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

export const getApiMediaById = <ThrowOnError extends boolean = false>(
	options: Options<GetApiMediaByIdData, ThrowOnError>,
): RequestResult<unknown, unknown, ThrowOnError> =>
	(options.client ?? client).get<unknown, unknown, ThrowOnError>({
		requestValidator: async (data) =>
			await z
				.object({
					body: z.never().optional(),
					path: zGetApiMediaByIdPath,
					query: z.never().optional(),
				})
				.parseAsync(data),
		url: "/api/media/{id}",
		...options,
	})

export const listMprisPlayers = <ThrowOnError extends boolean = false>(
	options?: Options<ListMprisPlayersData, ThrowOnError>,
): RequestResult<ListMprisPlayersResponses, unknown, ThrowOnError> =>
	(options?.client ?? client).get<ListMprisPlayersResponses, unknown, ThrowOnError>({
		requestValidator: async (data) =>
			await z
				.object({
					body: z.never().optional(),
					path: z.never().optional(),
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zListMprisPlayersResponse.parseAsync(data),
		url: "/api/mpris",
		...options,
	})

export const actOnMprisPlayer = <ThrowOnError extends boolean = false>(
	options: Options<ActOnMprisPlayerData, ThrowOnError>,
): RequestResult<ActOnMprisPlayerResponses, ActOnMprisPlayerErrors, ThrowOnError> =>
	(options.client ?? client).post<
		ActOnMprisPlayerResponses,
		ActOnMprisPlayerErrors,
		ThrowOnError
	>({
		requestValidator: async (data) =>
			await z
				.object({
					body: zActOnMprisPlayerBody,
					path: zActOnMprisPlayerPath,
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zActOnMprisPlayerResponse.parseAsync(data),
		url: "/api/mpris/{serviceName}/actions/{action}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	})

export const streamMprisPlayers = <ThrowOnError extends boolean = false>(
	options?: Options<StreamMprisPlayersData, ThrowOnError, StreamMprisPlayersResponse>,
): Promise<ServerSentEventsResult<StreamMprisPlayersResponses>> =>
	(options?.client ?? client).sse.get<
		StreamMprisPlayersResponses,
		StreamMprisPlayersErrors,
		ThrowOnError
	>({
		requestValidator: async (data) =>
			await z
				.object({
					body: z.never().optional(),
					path: z.never().optional(),
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zStreamMprisPlayersResponse.parseAsync(data),
		url: "/api/mpris/events",
		...options,
	})

export const listNotifications = <ThrowOnError extends boolean = false>(
	options?: Options<ListNotificationsData, ThrowOnError>,
): RequestResult<ListNotificationsResponses, ListNotificationsErrors, ThrowOnError> =>
	(options?.client ?? client).get<
		ListNotificationsResponses,
		ListNotificationsErrors,
		ThrowOnError
	>({
		requestValidator: async (data) =>
			await z
				.object({
					body: z.never().optional(),
					path: z.never().optional(),
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zListNotificationsResponse.parseAsync(data),
		url: "/api/notifications",
		...options,
	})

export const resizeNotifications = <ThrowOnError extends boolean = false>(
	options: Options<ResizeNotificationsData, ThrowOnError>,
): RequestResult<ResizeNotificationsResponses, ResizeNotificationsErrors, ThrowOnError> =>
	(options.client ?? client).post<
		ResizeNotificationsResponses,
		ResizeNotificationsErrors,
		ThrowOnError
	>({
		requestValidator: async (data) =>
			await z
				.object({
					body: zResizeNotificationsBody,
					path: z.never().optional(),
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zResizeNotificationsResponse.parseAsync(data),
		url: "/api/notifications/resize",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	})

export const dismissNotification = <ThrowOnError extends boolean = false>(
	options: Options<DismissNotificationData, ThrowOnError>,
): RequestResult<DismissNotificationResponses, DismissNotificationErrors, ThrowOnError> =>
	(options.client ?? client).delete<
		DismissNotificationResponses,
		DismissNotificationErrors,
		ThrowOnError
	>({
		requestValidator: async (data) =>
			await z
				.object({
					body: z.never().optional(),
					path: zDismissNotificationPath,
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zDismissNotificationResponse.parseAsync(data),
		url: "/api/notifications/{id}",
		...options,
	})

export const setNotificationPaused = <ThrowOnError extends boolean = false>(
	options: Options<SetNotificationPausedData, ThrowOnError>,
): RequestResult<SetNotificationPausedResponses, SetNotificationPausedErrors, ThrowOnError> =>
	(options.client ?? client).patch<
		SetNotificationPausedResponses,
		SetNotificationPausedErrors,
		ThrowOnError
	>({
		requestValidator: async (data) =>
			await z
				.object({
					body: zSetNotificationPausedBody,
					path: zSetNotificationPausedPath,
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zSetNotificationPausedResponse.parseAsync(data),
		url: "/api/notifications/{id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	})

export const invokeNotificationAction = <ThrowOnError extends boolean = false>(
	options: Options<InvokeNotificationActionData, ThrowOnError>,
): RequestResult<InvokeNotificationActionResponses, InvokeNotificationActionErrors, ThrowOnError> =>
	(options.client ?? client).post<
		InvokeNotificationActionResponses,
		InvokeNotificationActionErrors,
		ThrowOnError
	>({
		requestValidator: async (data) =>
			await z
				.object({
					body: z.never().optional(),
					path: zInvokeNotificationActionPath,
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zInvokeNotificationActionResponse.parseAsync(data),
		url: "/api/notifications/{id}/actions/{actionId}",
		...options,
	})

export const streamNotifications = <ThrowOnError extends boolean = false>(
	options?: Options<StreamNotificationsData, ThrowOnError, StreamNotificationsResponse>,
): Promise<ServerSentEventsResult<StreamNotificationsResponses>> =>
	(options?.client ?? client).sse.get<
		StreamNotificationsResponses,
		StreamNotificationsErrors,
		ThrowOnError
	>({
		requestValidator: async (data) =>
			await z
				.object({
					body: z.never().optional(),
					path: z.never().optional(),
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zStreamNotificationsResponse.parseAsync(data),
		url: "/api/notifications/events",
		...options,
	})

export const controlBento = <ThrowOnError extends boolean = false>(
	options: Options<ControlBentoData, ThrowOnError>,
): RequestResult<ControlBentoResponses, ControlBentoErrors, ThrowOnError> =>
	(options.client ?? client).post<ControlBentoResponses, ControlBentoErrors, ThrowOnError>({
		requestValidator: async (data) =>
			await z
				.object({
					body: zControlBentoBody,
					path: z.never().optional(),
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zControlBentoResponse.parseAsync(data),
		url: "/api/bento",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	})

export const streamCava = <ThrowOnError extends boolean = false>(
	options?: Options<StreamCavaData, ThrowOnError, StreamCavaResponse>,
): Promise<ServerSentEventsResult<StreamCavaResponses>> =>
	(options?.client ?? client).sse.get<StreamCavaResponses, StreamCavaErrors, ThrowOnError>({
		requestValidator: async (data) =>
			await z
				.object({
					body: z.never().optional(),
					path: z.never().optional(),
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zStreamCavaResponse.parseAsync(data),
		url: "/api/cava/events",
		...options,
	})

export const listNiriWorkspaces = <ThrowOnError extends boolean = false>(
	options?: Options<ListNiriWorkspacesData, ThrowOnError>,
): RequestResult<ListNiriWorkspacesResponses, unknown, ThrowOnError> =>
	(options?.client ?? client).get<ListNiriWorkspacesResponses, unknown, ThrowOnError>({
		requestValidator: async (data) =>
			await z
				.object({
					body: z.never().optional(),
					path: z.never().optional(),
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zListNiriWorkspacesResponse.parseAsync(data),
		url: "/api/niri",
		...options,
	})

export const focusNiriWorkspace = <ThrowOnError extends boolean = false>(
	options: Options<FocusNiriWorkspaceData, ThrowOnError>,
): RequestResult<FocusNiriWorkspaceResponses, FocusNiriWorkspaceErrors, ThrowOnError> =>
	(options.client ?? client).post<
		FocusNiriWorkspaceResponses,
		FocusNiriWorkspaceErrors,
		ThrowOnError
	>({
		requestValidator: async (data) =>
			await z
				.object({
					body: zFocusNiriWorkspaceBody,
					path: z.never().optional(),
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zFocusNiriWorkspaceResponse.parseAsync(data),
		url: "/api/niri/focus-workspace",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	})

export const streamNiriEvents = <ThrowOnError extends boolean = false>(
	options?: Options<StreamNiriEventsData, ThrowOnError, StreamNiriEventsResponse>,
): Promise<ServerSentEventsResult<StreamNiriEventsResponses>> =>
	(options?.client ?? client).sse.get<
		StreamNiriEventsResponses,
		StreamNiriEventsErrors,
		ThrowOnError
	>({
		requestValidator: async (data) =>
			await z
				.object({
					body: z.never().optional(),
					path: z.never().optional(),
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zStreamNiriEventsResponse.parseAsync(data),
		url: "/api/niri/events",
		...options,
	})

export const lockSystem = <ThrowOnError extends boolean = false>(
	options?: Options<LockSystemData, ThrowOnError>,
): RequestResult<LockSystemResponses, unknown, ThrowOnError> =>
	(options?.client ?? client).post<LockSystemResponses, unknown, ThrowOnError>({
		requestValidator: async (data) =>
			await z
				.object({
					body: z.never().optional(),
					path: z.never().optional(),
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zLockSystemResponse.parseAsync(data),
		url: "/api/system/lock",
		...options,
	})

export const suspendSystem = <ThrowOnError extends boolean = false>(
	options?: Options<SuspendSystemData, ThrowOnError>,
): RequestResult<SuspendSystemResponses, unknown, ThrowOnError> =>
	(options?.client ?? client).post<SuspendSystemResponses, unknown, ThrowOnError>({
		requestValidator: async (data) =>
			await z
				.object({
					body: z.never().optional(),
					path: z.never().optional(),
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zSuspendSystemResponse.parseAsync(data),
		url: "/api/system/suspend",
		...options,
	})

export const rebootSystem = <ThrowOnError extends boolean = false>(
	options?: Options<RebootSystemData, ThrowOnError>,
): RequestResult<RebootSystemResponses, unknown, ThrowOnError> =>
	(options?.client ?? client).post<RebootSystemResponses, unknown, ThrowOnError>({
		requestValidator: async (data) =>
			await z
				.object({
					body: z.never().optional(),
					path: z.never().optional(),
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zRebootSystemResponse.parseAsync(data),
		url: "/api/system/reboot",
		...options,
	})

export const shutdownSystem = <ThrowOnError extends boolean = false>(
	options?: Options<ShutdownSystemData, ThrowOnError>,
): RequestResult<ShutdownSystemResponses, unknown, ThrowOnError> =>
	(options?.client ?? client).post<ShutdownSystemResponses, unknown, ThrowOnError>({
		requestValidator: async (data) =>
			await z
				.object({
					body: z.never().optional(),
					path: z.never().optional(),
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zShutdownSystemResponse.parseAsync(data),
		url: "/api/system/shutdown",
		...options,
	})

export const logoutSystem = <ThrowOnError extends boolean = false>(
	options?: Options<LogoutSystemData, ThrowOnError>,
): RequestResult<LogoutSystemResponses, unknown, ThrowOnError> =>
	(options?.client ?? client).post<LogoutSystemResponses, unknown, ThrowOnError>({
		requestValidator: async (data) =>
			await z
				.object({
					body: z.never().optional(),
					path: z.never().optional(),
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zLogoutSystemResponse.parseAsync(data),
		url: "/api/system/logout",
		...options,
	})

export const getSystemStatus = <ThrowOnError extends boolean = false>(
	options?: Options<GetSystemStatusData, ThrowOnError>,
): RequestResult<GetSystemStatusResponses, unknown, ThrowOnError> =>
	(options?.client ?? client).get<GetSystemStatusResponses, unknown, ThrowOnError>({
		requestValidator: async (data) =>
			await z
				.object({
					body: z.never().optional(),
					path: z.never().optional(),
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zGetSystemStatusResponse.parseAsync(data),
		url: "/api/system",
		...options,
	})

export const getConfiguredTimezone = <ThrowOnError extends boolean = false>(
	options?: Options<GetConfiguredTimezoneData, ThrowOnError>,
): RequestResult<GetConfiguredTimezoneResponses, unknown, ThrowOnError> =>
	(options?.client ?? client).get<GetConfiguredTimezoneResponses, unknown, ThrowOnError>({
		requestValidator: async (data) =>
			await z
				.object({
					body: z.never().optional(),
					path: z.never().optional(),
					query: z.never().optional(),
				})
				.parseAsync(data),
		responseValidator: async (data) => await zGetConfiguredTimezoneResponse.parseAsync(data),
		url: "/api/timezone",
		...options,
	})
