// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: `${string}://${string}` | (string & {})
}

export type GetApiMediaByIdData = {
	body?: never
	path: {
		id: string
	}
	query?: never
	url: "/api/media/{id}"
}

export type ListMprisPlayersData = {
	body?: never
	path?: never
	query?: never
	url: "/api/mpris"
}

export type ListMprisPlayersResponses = {
	/**
	 * Response for status 200
	 */
	200: Array<{
		serviceName: string
		identity: string
		playbackStatus: string
		title: string
		artist: string
		album: string
		artUrl: string
		position: number
		length: number
		canPlay: boolean
		canPause: boolean
		canGoNext: boolean
		canGoPrevious: boolean
	}>
}

export type ListMprisPlayersResponse = ListMprisPlayersResponses[keyof ListMprisPlayersResponses]

export type ActOnMprisPlayerData = {
	body: {
		offset?: number
	}
	path: {
		serviceName: string
		action: "playPause" | "next" | "previous" | "seek"
	}
	query?: never
	url: "/api/mpris/{serviceName}/actions/{action}"
}

export type ActOnMprisPlayerErrors = {
	/**
	 * Response for status 503
	 */
	503: string
}

export type ActOnMprisPlayerError = ActOnMprisPlayerErrors[keyof ActOnMprisPlayerErrors]

export type ActOnMprisPlayerResponses = {
	/**
	 * Response for status 200
	 */
	200: {
		ok: true
	}
}

export type ActOnMprisPlayerResponse = ActOnMprisPlayerResponses[keyof ActOnMprisPlayerResponses]

export type StreamMprisPlayersData = {
	body?: never
	path?: never
	query?: never
	url: "/api/mpris/events"
}

export type StreamMprisPlayersErrors = {
	/**
	 * MPRIS unavailable
	 */
	503: unknown
}

export type StreamMprisPlayersResponses = {
	/**
	 * MPRIS player updates
	 */
	200: Array<{
		serviceName: string
		identity: string
		playbackStatus: string
		title: string
		artist: string
		album: string
		artUrl: string
		position: number
		length: number
		canPlay: boolean
		canPause: boolean
		canGoNext: boolean
		canGoPrevious: boolean
	}>
}

export type StreamMprisPlayersResponse =
	StreamMprisPlayersResponses[keyof StreamMprisPlayersResponses]

export type ListNotificationsData = {
	body?: never
	path?: never
	query?: never
	url: "/api/notifications"
}

export type ListNotificationsErrors = {
	/**
	 * Response for status 503
	 */
	503: string
}

export type ListNotificationsError = ListNotificationsErrors[keyof ListNotificationsErrors]

export type ListNotificationsResponses = {
	/**
	 * Response for status 200
	 */
	200: Array<{
		id: number
		appName: string
		appIcon: string
		summary: string
		body: string
		actions: Array<{
			id: string
			label: string
		}>
		urgency: number
		category: string
		resident: boolean
		transient: boolean
		receivedAt: number
		expiresAt: number | null
		visualExpiresAt: number | null
	}>
}

export type ListNotificationsResponse = ListNotificationsResponses[keyof ListNotificationsResponses]

export type ResizeNotificationsData = {
	body: {
		height: number
	}
	path?: never
	query?: never
	url: "/api/notifications/resize"
}

export type ResizeNotificationsErrors = {
	/**
	 * Response for status 503
	 */
	503: string
}

export type ResizeNotificationsError = ResizeNotificationsErrors[keyof ResizeNotificationsErrors]

export type ResizeNotificationsResponses = {
	/**
	 * Response for status 200
	 */
	200: {
		ok: true
	}
}

export type ResizeNotificationsResponse =
	ResizeNotificationsResponses[keyof ResizeNotificationsResponses]

export type DismissNotificationData = {
	body?: never
	path: {
		id: number
	}
	query?: never
	url: "/api/notifications/{id}"
}

export type DismissNotificationErrors = {
	/**
	 * Response for status 404
	 */
	404: string
	/**
	 * Response for status 503
	 */
	503: string
}

export type DismissNotificationError = DismissNotificationErrors[keyof DismissNotificationErrors]

export type DismissNotificationResponses = {
	/**
	 * Response for status 200
	 */
	200: {
		ok: true
	}
}

export type DismissNotificationResponse =
	DismissNotificationResponses[keyof DismissNotificationResponses]

export type SetNotificationPausedData = {
	body: {
		paused: boolean
	}
	path: {
		id: number
	}
	query?: never
	url: "/api/notifications/{id}"
}

export type SetNotificationPausedErrors = {
	/**
	 * Response for status 404
	 */
	404: string
	/**
	 * Response for status 503
	 */
	503: string
}

export type SetNotificationPausedError =
	SetNotificationPausedErrors[keyof SetNotificationPausedErrors]

export type SetNotificationPausedResponses = {
	/**
	 * Response for status 200
	 */
	200: {
		ok: true
	}
}

export type SetNotificationPausedResponse =
	SetNotificationPausedResponses[keyof SetNotificationPausedResponses]

export type InvokeNotificationActionData = {
	body?: never
	path: {
		id: number
		actionId: string
	}
	query?: never
	url: "/api/notifications/{id}/actions/{actionId}"
}

export type InvokeNotificationActionErrors = {
	/**
	 * Response for status 404
	 */
	404: string
	/**
	 * Response for status 503
	 */
	503: string
}

export type InvokeNotificationActionError =
	InvokeNotificationActionErrors[keyof InvokeNotificationActionErrors]

export type InvokeNotificationActionResponses = {
	/**
	 * Response for status 200
	 */
	200: {
		ok: true
	}
}

export type InvokeNotificationActionResponse =
	InvokeNotificationActionResponses[keyof InvokeNotificationActionResponses]

export type StreamNotificationsData = {
	body?: never
	path?: never
	query?: never
	url: "/api/notifications/events"
}

export type StreamNotificationsErrors = {
	/**
	 * Notifications unavailable
	 */
	503: unknown
}

export type StreamNotificationsResponses = {
	/**
	 * Notification updates
	 */
	200: Array<{
		id: number
		appName: string
		appIcon: string
		summary: string
		body: string
		actions: Array<{
			id: string
			label: string
		}>
		urgency: number
		category: string
		resident: boolean
		transient: boolean
		receivedAt: number
		expiresAt: number | null
		visualExpiresAt: number | null
	}>
}

export type StreamNotificationsResponse =
	StreamNotificationsResponses[keyof StreamNotificationsResponses]

export type ControlBentoData = {
	body: {
		action: "open" | "close" | "toggle"
	}
	path?: never
	query?: never
	url: "/api/bento"
}

export type ControlBentoErrors = {
	/**
	 * Response for status 503
	 */
	503: string
}

export type ControlBentoError = ControlBentoErrors[keyof ControlBentoErrors]

export type ControlBentoResponses = {
	/**
	 * Response for status 200
	 */
	200: {
		ok: true
	}
}

export type ControlBentoResponse = ControlBentoResponses[keyof ControlBentoResponses]

export type StreamCavaData = {
	body?: never
	path?: never
	query?: never
	url: "/api/cava/events"
}

export type StreamCavaErrors = {
	/**
	 * Cava unavailable
	 */
	503: unknown
}

export type StreamCavaResponses = {
	/**
	 * Cava audio frames
	 */
	200: Array<number>
}

export type StreamCavaResponse = StreamCavaResponses[keyof StreamCavaResponses]

export type ListNiriWorkspacesData = {
	body?: never
	path?: never
	query?: never
	url: "/api/niri"
}

export type ListNiriWorkspacesResponses = {
	/**
	 * Response for status 200
	 */
	200: Array<{
		id: number
		idx: number
		name: string | null
		output: string | null
		is_urgent: boolean
		is_active: boolean
		is_focused: boolean
		active_window_id: number | null
	}>
}

export type ListNiriWorkspacesResponse =
	ListNiriWorkspacesResponses[keyof ListNiriWorkspacesResponses]

export type FocusNiriWorkspaceData = {
	body: {
		index: number
	}
	path?: never
	query?: never
	url: "/api/niri/focus-workspace"
}

export type FocusNiriWorkspaceErrors = {
	/**
	 * Response for status 503
	 */
	503: string
}

export type FocusNiriWorkspaceError = FocusNiriWorkspaceErrors[keyof FocusNiriWorkspaceErrors]

export type FocusNiriWorkspaceResponses = {
	/**
	 * Response for status 200
	 */
	200: {
		ok: true
	}
}

export type FocusNiriWorkspaceResponse =
	FocusNiriWorkspaceResponses[keyof FocusNiriWorkspaceResponses]

export type StreamNiriEventsData = {
	body?: never
	path?: never
	query?: never
	url: "/api/niri/events"
}

export type StreamNiriEventsErrors = {
	/**
	 * Niri unavailable
	 */
	503: unknown
}

export type StreamNiriEventsResponses = {
	/**
	 * Raw Niri event updates
	 */
	200: {
		[key: string]: unknown
	}
}

export type StreamNiriEventsResponse = StreamNiriEventsResponses[keyof StreamNiriEventsResponses]

export type LockSystemData = {
	body?: never
	path?: never
	query?: never
	url: "/api/system/lock"
}

export type LockSystemResponses = {
	/**
	 * Response for status 200
	 */
	200: {
		ok: true
	}
}

export type LockSystemResponse = LockSystemResponses[keyof LockSystemResponses]

export type SuspendSystemData = {
	body?: never
	path?: never
	query?: never
	url: "/api/system/suspend"
}

export type SuspendSystemResponses = {
	/**
	 * Response for status 200
	 */
	200: {
		ok: true
	}
}

export type SuspendSystemResponse = SuspendSystemResponses[keyof SuspendSystemResponses]

export type RebootSystemData = {
	body?: never
	path?: never
	query?: never
	url: "/api/system/reboot"
}

export type RebootSystemResponses = {
	/**
	 * Response for status 200
	 */
	200: {
		ok: true
	}
}

export type RebootSystemResponse = RebootSystemResponses[keyof RebootSystemResponses]

export type ShutdownSystemData = {
	body?: never
	path?: never
	query?: never
	url: "/api/system/shutdown"
}

export type ShutdownSystemResponses = {
	/**
	 * Response for status 200
	 */
	200: {
		ok: true
	}
}

export type ShutdownSystemResponse = ShutdownSystemResponses[keyof ShutdownSystemResponses]

export type LogoutSystemData = {
	body?: never
	path?: never
	query?: never
	url: "/api/system/logout"
}

export type LogoutSystemResponses = {
	/**
	 * Response for status 200
	 */
	200: {
		ok: true
	}
}

export type LogoutSystemResponse = LogoutSystemResponses[keyof LogoutSystemResponses]

export type GetSystemStatusData = {
	body?: never
	path?: never
	query?: never
	url: "/api/system"
}

export type GetSystemStatusResponses = {
	/**
	 * Response for status 200
	 */
	200: {
		battery: {
			capacity: number | null
			charging: boolean
		}
	}
}

export type GetSystemStatusResponse = GetSystemStatusResponses[keyof GetSystemStatusResponses]

export type GetConfiguredTimezoneData = {
	body?: never
	path?: never
	query?: never
	url: "/api/timezone"
}

export type GetConfiguredTimezoneResponses = {
	/**
	 * Response for status 200
	 */
	200: {
		timezone: string
	}
}

export type GetConfiguredTimezoneResponse =
	GetConfiguredTimezoneResponses[keyof GetConfiguredTimezoneResponses]
