// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod"

export const zGetApiMediaByIdPath = z.object({
	id: z.string(),
})

/**
 * Response for status 200
 */
export const zListMprisPlayersResponse = z.array(
	z.object({
		serviceName: z.string(),
		identity: z.string(),
		playbackStatus: z.string(),
		title: z.string(),
		artist: z.string(),
		album: z.string(),
		artUrl: z.string(),
		position: z.number(),
		length: z.number(),
		canPlay: z.boolean(),
		canPause: z.boolean(),
		canGoNext: z.boolean(),
		canGoPrevious: z.boolean(),
	}),
)

export const zActOnMprisPlayerBody = z.object({
	offset: z.number().optional(),
})

export const zActOnMprisPlayerPath = z.object({
	serviceName: z.string().min(1),
	action: z.enum(["playPause", "next", "previous", "seek"]),
})

/**
 * Response for status 200
 */
export const zActOnMprisPlayerResponse = z.object({
	ok: z.literal(true),
})

/**
 * MPRIS player updates
 */
export const zStreamMprisPlayersResponse = z.array(
	z.object({
		serviceName: z.string(),
		identity: z.string(),
		playbackStatus: z.string(),
		title: z.string(),
		artist: z.string(),
		album: z.string(),
		artUrl: z.string(),
		position: z.number(),
		length: z.number(),
		canPlay: z.boolean(),
		canPause: z.boolean(),
		canGoNext: z.boolean(),
		canGoPrevious: z.boolean(),
	}),
)

/**
 * Response for status 200
 */
export const zListNotificationsResponse = z.array(
	z.object({
		id: z.int().gt(0).lte(9007199254740991),
		appName: z.string(),
		appIcon: z.string(),
		summary: z.string(),
		body: z.string(),
		actions: z.array(
			z.object({
				id: z.string(),
				label: z.string(),
			}),
		),
		urgency: z.int().gte(0).lte(2),
		category: z.string(),
		resident: z.boolean(),
		transient: z.boolean(),
		receivedAt: z.int().gte(0).lte(9007199254740991),
		expiresAt: z.int().gt(0).lte(9007199254740991).nullable(),
		visualExpiresAt: z.int().gt(0).lte(9007199254740991).nullable(),
	}),
)

export const zResizeNotificationsBody = z.object({
	height: z.number().gte(0).lte(10000),
})

/**
 * Response for status 200
 */
export const zResizeNotificationsResponse = z.object({
	ok: z.literal(true),
})

export const zDismissNotificationPath = z.object({
	id: z.int().gt(0).lte(9007199254740991),
})

/**
 * Response for status 200
 */
export const zDismissNotificationResponse = z.object({
	ok: z.literal(true),
})

export const zSetNotificationPausedBody = z.object({
	paused: z.boolean(),
})

export const zSetNotificationPausedPath = z.object({
	id: z.int().gt(0).lte(9007199254740991),
})

/**
 * Response for status 200
 */
export const zSetNotificationPausedResponse = z.object({
	ok: z.literal(true),
})

export const zInvokeNotificationActionPath = z.object({
	id: z.int().gt(0).lte(9007199254740991),
	actionId: z.string().min(1),
})

/**
 * Response for status 200
 */
export const zInvokeNotificationActionResponse = z.object({
	ok: z.literal(true),
})

/**
 * Notification updates
 */
export const zStreamNotificationsResponse = z.array(
	z.object({
		id: z.int().gt(0).lte(9007199254740991),
		appName: z.string(),
		appIcon: z.string(),
		summary: z.string(),
		body: z.string(),
		actions: z.array(
			z.object({
				id: z.string(),
				label: z.string(),
			}),
		),
		urgency: z.int().gte(0).lte(2),
		category: z.string(),
		resident: z.boolean(),
		transient: z.boolean(),
		receivedAt: z.int().gte(0).lte(9007199254740991),
		expiresAt: z.int().gt(0).lte(9007199254740991).nullable(),
		visualExpiresAt: z.int().gt(0).lte(9007199254740991).nullable(),
	}),
)

export const zControlBentoBody = z.object({
	action: z.enum(["open", "close", "toggle"]),
})

/**
 * Response for status 200
 */
export const zControlBentoResponse = z.object({
	ok: z.literal(true),
})

/**
 * Cava audio frames
 */
export const zStreamCavaResponse = z.array(z.number())

/**
 * Response for status 200
 */
export const zListNiriWorkspacesResponse = z.array(
	z.object({
		id: z.number(),
		idx: z.number(),
		name: z.string().nullable(),
		output: z.string().nullable(),
		is_urgent: z.boolean(),
		is_active: z.boolean(),
		is_focused: z.boolean(),
		active_window_id: z.number().nullable(),
	}),
)

export const zFocusNiriWorkspaceBody = z.object({
	index: z.int().gt(0).lte(9007199254740991),
})

/**
 * Response for status 200
 */
export const zFocusNiriWorkspaceResponse = z.object({
	ok: z.literal(true),
})

/**
 * Raw Niri event updates
 */
export const zStreamNiriEventsResponse = z.record(z.string(), z.unknown())

/**
 * Response for status 200
 */
export const zLockSystemResponse = z.object({
	ok: z.literal(true),
})

/**
 * Response for status 200
 */
export const zSuspendSystemResponse = z.object({
	ok: z.literal(true),
})

/**
 * Response for status 200
 */
export const zRebootSystemResponse = z.object({
	ok: z.literal(true),
})

/**
 * Response for status 200
 */
export const zShutdownSystemResponse = z.object({
	ok: z.literal(true),
})

/**
 * Response for status 200
 */
export const zLogoutSystemResponse = z.object({
	ok: z.literal(true),
})

/**
 * Response for status 200
 */
export const zGetSystemStatusResponse = z.object({
	battery: z.object({
		capacity: z.number().nullable(),
		charging: z.boolean(),
	}),
})

/**
 * Response for status 200
 */
export const zGetConfiguredTimezoneResponse = z.object({
	timezone: z.string(),
})
