// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from "./client"
import { client } from "./client.gen"
import type {
	DeleteLayerShellWindowData,
	DeleteLayerShellWindowErrors,
	DeleteLayerShellWindowResponses,
	HealthData,
	HealthErrors,
	HealthResponses,
	ListLayerShellWindowsData,
	ListLayerShellWindowsErrors,
	ListLayerShellWindowsResponses,
	LockData,
	LockErrors,
	LockResponses,
	QuitData,
	QuitErrors,
	QuitResponses,
	SessionLockStatusData,
	SessionLockStatusErrors,
	SessionLockStatusResponses,
	UnlockData,
	UnlockErrors,
	UnlockResponses,
	UpdateLayerShellWindowData,
	UpdateLayerShellWindowErrors,
	UpdateLayerShellWindowResponses,
} from "./types.gen"

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
	TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * Check host availability
 *
 * Returns once the Rocket host API is accepting authenticated requests.
 */
export const health = <ThrowOnError extends boolean = false>(
	options?: Options<HealthData, ThrowOnError>,
): RequestResult<HealthResponses, HealthErrors, ThrowOnError> =>
	(options?.client ?? client).get<HealthResponses, HealthErrors, ThrowOnError>({
		security: [{ scheme: "bearer", type: "http" }],
		url: "/health",
		...options,
	})

/**
 * List managed layer-shell windows
 *
 * Returns the currently managed layer-shell windows and their identifiers.
 */
export const listLayerShellWindows = <ThrowOnError extends boolean = false>(
	options?: Options<ListLayerShellWindowsData, ThrowOnError>,
): RequestResult<ListLayerShellWindowsResponses, ListLayerShellWindowsErrors, ThrowOnError> =>
	(options?.client ?? client).get<
		ListLayerShellWindowsResponses,
		ListLayerShellWindowsErrors,
		ThrowOnError
	>({
		security: [{ scheme: "bearer", type: "http" }],
		url: "/layer-shell",
		...options,
	})

/**
 * Close a layer-shell window
 *
 * Closes the window identified by `id`. Mutations for the same ID are serialized, and the response is returned after GTK processes the command. Unknown IDs leave the managed window set unchanged.
 */
export const deleteLayerShellWindow = <ThrowOnError extends boolean = false>(
	options: Options<DeleteLayerShellWindowData, ThrowOnError>,
): RequestResult<DeleteLayerShellWindowResponses, DeleteLayerShellWindowErrors, ThrowOnError> =>
	(options.client ?? client).delete<
		DeleteLayerShellWindowResponses,
		DeleteLayerShellWindowErrors,
		ThrowOnError
	>({
		security: [{ scheme: "bearer", type: "http" }],
		url: "/layer-shell/{id}",
		...options,
	})

/**
 * Update a layer-shell window
 *
 * Creates the window when `id` is unknown, or updates the existing window in place. Mutations for the same ID are serialized, and the response is returned after GTK processes the command.
 */
export const updateLayerShellWindow = <ThrowOnError extends boolean = false>(
	options: Options<UpdateLayerShellWindowData, ThrowOnError>,
): RequestResult<UpdateLayerShellWindowResponses, UpdateLayerShellWindowErrors, ThrowOnError> =>
	(options.client ?? client).put<
		UpdateLayerShellWindowResponses,
		UpdateLayerShellWindowErrors,
		ThrowOnError
	>({
		security: [{ scheme: "bearer", type: "http" }],
		url: "/layer-shell/{id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	})

/**
 * Request host shutdown
 *
 * With `--webapp-command`, requests graceful Rocket shutdown and sends the supervised child `SIGTERM` (then `SIGKILL` after five seconds). Otherwise, sends the shell an `/_quit` callback. Repeated requests do not repeat shutdown notification.
 */
export const quit = <ThrowOnError extends boolean = false>(
	options?: Options<QuitData, ThrowOnError>,
): RequestResult<QuitResponses, QuitErrors, ThrowOnError> =>
	(options?.client ?? client).post<QuitResponses, QuitErrors, ThrowOnError>({
		security: [{ scheme: "bearer", type: "http" }],
		url: "/quit",
		...options,
	})

/**
 * Get session-lock status
 *
 * Returns the most recently observed session-lock state. `pending` means a lock was requested but compositor confirmation has not arrived.
 */
export const sessionLockStatus = <ThrowOnError extends boolean = false>(
	options?: Options<SessionLockStatusData, ThrowOnError>,
): RequestResult<SessionLockStatusResponses, SessionLockStatusErrors, ThrowOnError> =>
	(options?.client ?? client).get<
		SessionLockStatusResponses,
		SessionLockStatusErrors,
		ThrowOnError
	>({
		security: [{ scheme: "bearer", type: "http" }],
		url: "/session-lock",
		...options,
	})

/**
 * Request session lock
 *
 * Queues a session-lock request that loads the supplied URL on each lock surface. `202 Accepted` confirms queueing; poll the status endpoint for compositor success or failure.
 */
export const lock = <ThrowOnError extends boolean = false>(
	options: Options<LockData, ThrowOnError>,
): RequestResult<LockResponses, LockErrors, ThrowOnError> =>
	(options.client ?? client).post<LockResponses, LockErrors, ThrowOnError>({
		security: [{ scheme: "bearer", type: "http" }],
		url: "/session-lock/lock",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	})

/**
 * Request session unlock
 *
 * Queues session unlock. `202 Accepted` confirms queueing; poll the status endpoint until it reports `unlocked`.
 */
export const unlock = <ThrowOnError extends boolean = false>(
	options?: Options<UnlockData, ThrowOnError>,
): RequestResult<UnlockResponses, UnlockErrors, ThrowOnError> =>
	(options?.client ?? client).post<UnlockResponses, UnlockErrors, ThrowOnError>({
		security: [{ scheme: "bearer", type: "http" }],
		url: "/session-lock/unlock",
		...options,
	})
