// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: `${string}://${string}` | (string & {})
}

export type Webhooks =
	ReceiveEventsWebhookRequest | ReceiveQuitWebhookRequest | ReceiveStartWebhookRequest

/**
 * Space reserved by the layer-shell surface.
 */
export type ExclusiveZone =
	| {
			mode: "none"
	  }
	| {
			mode: "auto"
	  }
	| {
			mode: "fixed"
			/**
			 * Reserve an exact logical-pixel size.
			 */
			value: number
	  }

/**
 * Liveness response from the native host.
 */
export type HealthResponse = {
	/**
	 * Always `ok` when the host accepts requests.
	 */
	status: string
}

/**
 * Keyboard focus behavior requested from wlr-layer-shell.
 */
export type KeyboardMode = "none" | "on-demand" | "exclusive"

/**
 * Stacking layer requested from wlr-layer-shell.
 */
export type Layer = "background" | "bottom" | "top" | "overlay"

/**
 * Edges to which the layer-shell surface is anchored.
 */
export type LayerShellAnchors = {
	/**
	 * Anchor to the bottom edge.
	 */
	bottom?: boolean
	/**
	 * Anchor to the left edge.
	 */
	left?: boolean
	/**
	 * Anchor to the right edge.
	 */
	right?: boolean
	/**
	 * Anchor to the top edge.
	 */
	top?: boolean
}

/**
 * Per-edge layer-shell margins in logical pixels.
 */
export type LayerShellMargins = {
	/**
	 * Bottom margin.
	 */
	bottom?: number
	/**
	 * Left margin.
	 */
	left?: number
	/**
	 * Right margin.
	 */
	right?: number
	/**
	 * Top margin.
	 */
	top?: number
}

/**
 * Configuration for a wlr-layer-shell window.
 */
export type LayerShellWindowSpec = {
	/**
	 * Screen edges to which the surface is anchored.
	 */
	anchors?: LayerShellAnchors
	/**
	 * Space reserved from other surfaces.
	 */
	exclusiveZone?: ExclusiveZone
	/**
	 * Optional logical height. Defaults to 240 when omitted.
	 */
	height?: number | null
	/**
	 * Keyboard focus behavior for the surface.
	 */
	keyboardMode?: KeyboardMode
	/**
	 * Compositor layer for the surface.
	 */
	layer?: Layer
	/**
	 * Offset from each anchored screen edge, in logical pixels.
	 */
	margins?: LayerShellMargins
	/**
	 * Output/monitor name. `None` lets the compositor choose.
	 */
	monitor?: string | null
	/**
	 * Optional compositor namespace used to identify this surface.
	 */
	namespace?: string | null
	/**
	 * URL loaded in the window's web view.
	 */
	url: string
	/**
	 * Whether the window is mapped and visible.
	 */
	visible?: boolean | null
	/**
	 * Optional logical width. Defaults to 500 when omitted.
	 */
	width?: number | null
}

/**
 * Snapshot entry for one managed layer-shell window.
 */
export type LayerShellWindowState = LayerShellWindowSpec & {
	/**
	 * Identifier used by the layer-shell API path.
	 */
	id: string
}

/**
 * Layer-shell window listing response.
 */
export type LayerShellWindowsResponse = {
	layerShellWindows: Array<LayerShellWindowState>
}

/**
 * Accepted native-host shutdown request.
 */
export type QuitResponse = {
	/**
	 * Always `shutting down` for an accepted request.
	 */
	status: string
}

/**
 * URL loaded on every session-lock surface.
 */
export type SessionLockRequest = {
	/**
	 * URL loaded in each compositor-provided lock surface.
	 */
	url: string
}

/**
 * Lifecycle state reported by the session-lock compositor protocol.
 */
export type SessionLockState = "unlocked" | "pending" | "locked" | "failed"

/**
 * Current session-lock lifecycle state.
 */
export type SessionLockStatus = {
	/**
	 * Most recently observed compositor state.
	 */
	state: SessionLockState
}

export type HealthData = {
	body?: never
	path?: never
	query?: never
	url: "/health"
}

export type HealthErrors = {
	/**
	 * Missing or invalid bearer token
	 */
	401: unknown
}

export type HealthResponses = {
	/**
	 * Host is alive
	 */
	200: HealthResponse
}

export type HealthResponse2 = HealthResponses[keyof HealthResponses]

export type ListLayerShellWindowsData = {
	body?: never
	path?: never
	query?: never
	url: "/layer-shell"
}

export type ListLayerShellWindowsErrors = {
	/**
	 * Missing or invalid bearer token
	 */
	401: unknown
}

export type ListLayerShellWindowsResponses = {
	/**
	 * Current layer-shell windows
	 */
	200: LayerShellWindowsResponse
}

export type ListLayerShellWindowsResponse =
	ListLayerShellWindowsResponses[keyof ListLayerShellWindowsResponses]

export type DeleteLayerShellWindowData = {
	body?: never
	path: {
		/**
		 * Layer-shell window identifier
		 */
		id: string
	}
	query?: never
	url: "/layer-shell/{id}"
}

export type DeleteLayerShellWindowErrors = {
	/**
	 * Missing or invalid bearer token
	 */
	401: unknown
	/**
	 * GTK application command channel is unavailable
	 */
	503: unknown
}

export type DeleteLayerShellWindowResponses = {
	/**
	 * Layer-shell window close processed
	 */
	204: void
}

export type DeleteLayerShellWindowResponse =
	DeleteLayerShellWindowResponses[keyof DeleteLayerShellWindowResponses]

export type UpdateLayerShellWindowData = {
	body: LayerShellWindowSpec
	path: {
		/**
		 * Layer-shell window identifier
		 */
		id: string
	}
	query?: never
	url: "/layer-shell/{id}"
}

export type UpdateLayerShellWindowErrors = {
	/**
	 * Invalid request body
	 */
	400: unknown
	/**
	 * Missing or invalid bearer token
	 */
	401: unknown
	/**
	 * GTK application command channel is unavailable
	 */
	503: unknown
}

export type UpdateLayerShellWindowResponses = {
	/**
	 * Layer-shell window update processed
	 */
	204: void
}

export type UpdateLayerShellWindowResponse =
	UpdateLayerShellWindowResponses[keyof UpdateLayerShellWindowResponses]

export type QuitData = {
	body?: never
	path?: never
	query?: never
	url: "/quit"
}

export type QuitErrors = {
	/**
	 * Missing or invalid bearer token
	 */
	401: unknown
}

export type QuitResponses = {
	/**
	 * Graceful host shutdown requested
	 */
	202: QuitResponse
}

export type QuitResponse2 = QuitResponses[keyof QuitResponses]

export type SessionLockStatusData = {
	body?: never
	path?: never
	query?: never
	url: "/session-lock"
}

export type SessionLockStatusErrors = {
	/**
	 * Missing or invalid bearer token
	 */
	401: unknown
}

export type SessionLockStatusResponses = {
	/**
	 * Current session-lock status
	 */
	200: SessionLockStatus
}

export type SessionLockStatusResponse = SessionLockStatusResponses[keyof SessionLockStatusResponses]

export type LockData = {
	body: SessionLockRequest
	path?: never
	query?: never
	url: "/session-lock/lock"
}

export type LockErrors = {
	/**
	 * Invalid request body
	 */
	400: unknown
	/**
	 * Missing or invalid bearer token
	 */
	401: unknown
	/**
	 * GTK application command channel is unavailable
	 */
	503: unknown
}

export type LockResponses = {
	/**
	 * Session lock requested
	 */
	202: unknown
}

export type UnlockData = {
	body?: never
	path?: never
	query?: never
	url: "/session-lock/unlock"
}

export type UnlockErrors = {
	/**
	 * Missing or invalid bearer token
	 */
	401: unknown
	/**
	 * GTK application command channel is unavailable
	 */
	503: unknown
}

export type UnlockResponses = {
	/**
	 * Session unlock requested
	 */
	202: unknown
}

export type ReceiveEventsWebhookPayload = string

export type ReceiveEventsWebhookRequest = {
	body: ReceiveEventsWebhookPayload
	key: "/_events"
	path?: never
	query?: never
}

export type ReceiveQuitWebhookRequest = {
	body?: never
	key: "/_quit"
	path?: never
	query?: never
}

export type ReceiveStartWebhookPayload = unknown

export type ReceiveStartWebhookRequest = {
	body: ReceiveStartWebhookPayload
	key: "/_start"
	path?: never
	query?: never
}
