[package]
name = "catppuccin_userstyles_extractor"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = [ "cargo", "derive" ] }
cssparser = "0.35.0"
glob = "0.3.3"
serde = { version = "1.0.219", features = [ "derive" ] }
serde_json = "1.0.143"
